// Fixed list of button colours used by the game.
const buttonColours = ["red", "blue", "green", "yellow"];

// Stores the sequence generated by the game.
let gamePattern = [];

// Stores the sequence entered by the player.
let userClickedPattern = [];

// Current game level.
let level = 0;

// Tracks whether the game is currently running.
let gameStarted = false;

// Generates the next colour in the game sequence.
function nextSequence() {

    // Pick a random index from buttonColours.
    const randomNumber = Math.floor(Math.random() * buttonColours.length);

    // Get the colour at that random index.
    const randomChosenColour = buttonColours[randomNumber];

    // Add the new colour to the game sequence.
    gamePattern.push(randomChosenColour);

    // Flash the chosen button.
    $("#" + randomChosenColour).fadeOut(75).fadeIn(75);

    // Play the sound for the chosen colour.
    playSound(randomChosenColour);

    // Move to the next level.
    level++;

    // Display the current level.
    $("h1").text("Level " + level);
}

// Handle player button clicks.
$(".btn").click(function(){
     // Store the colour the player clicked.
    userClickedPattern.push(this.id);

    // Play the clicked button's sound.
    playSound(this.id);

    // Show the pressed animation.
    pressAnimation(this.id);

     // Check whether the latest answer is correct.
    checkAnswer(userClickedPattern.length - 1);
});

// Start the game when the player presses any key.
$(document).on("keydown", function(){
    // Only start a new game if one isn't already running.
    if(!gameStarted){
        nextSequence();
        gameStarted = true;
    }
});

// Plays the sound associated with a colour.
function playSound(name){

    // Create an audio object using the colour's sound file.
    let audio = new Audio(`./sounds/${name}.mp3`);

    // Play the sound.
    audio.play();
}

// Temporarily shows the pressed-button animation.
function pressAnimation(currentColour){
     // Add the pressed class to the clicked button.
    $("#" + currentColour).addClass("pressed");

    // Remove the class after 100ms.
    setTimeout(() =>{
        $("#" + currentColour).removeClass("pressed");
    },100);
}

// Checks the player's latest answer.
function checkAnswer(currentIndex){
     // Compare the player's answer with the game's sequence.
    if(gamePattern[currentIndex] === userClickedPattern[currentIndex]){

        // If the entire sequence is correct, move to the next level.
        if(gamePattern.length === userClickedPattern.length){
            setTimeout(() =>{
                nextSequence();

                // Clear the player's previous answers.
                userClickedPattern.length = 0;
            },1000);
        }
    }
    else{
        // Play the wrong-answer sound.
        playSound("wrong");

         // Flash the screen red.
        $("body").addClass("game-over");

        // Remove the red flash after 200ms.
        setTimeout(() =>{
            $("body").removeClass("game-over");
        }, 200);

         // Tell the player that the game is over.
        $("h1").text("Game Over, Press Any Key to Restart");

        // Reset the game state.
        startOver();
    }
}

// Resets everything needed for a new game.
function startOver(){

    // Allow the next keypress to start a new game.
    gameStarted = false;

    // Reset the level.
    level = 0;

    // Clear the game's sequence.
    gamePattern.length = 0;

    // Clear the player's previous answers.
    userClickedPattern.length = 0;
}